name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: 'Fix openssl'
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'buildingblocs'
        reponame: 'starvation-frontend'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
